docs(readme): update readme & add contributing.md
NativeScript/nativescript-dev-typescript pull request #43
Opened 2018-02-06 14:42 UTC by radeva

2018-02-06 14:51 UTC, Mitko-Kerezov requested changes

2018-02-06 14:51 UTC, Mitko-Kerezov commented on CONTRIBUTING.md
> +#In the repo root
I'd prefer a white space after `#` so that it becomes 
`# In the repo root`

2018-02-06 14:51 UTC, Mitko-Kerezov commented on README.md
> + - `typescript` as dependency
`typescript` will actually be a dev-dependency

2018-02-07 12:51 UTC, radeva commented
@Mitko-Kerezov Comments are addressed.

2018-02-07 12:52 UTC, Mitko-Kerezov approved these changes
Looks okay to me

2018-02-16 08:09 UTC, merged